<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('school_settings', function (Blueprint $table) {
            $table->id(); $table->string('school_name')->default('Ghana School'); $table->string('logo_path')->nullable(); $table->string('phone')->nullable(); $table->string('email')->nullable(); $table->text('address')->nullable(); $table->string('currency',3)->default('GHS'); $table->string('admission_prefix')->default('ADM'); $table->unsignedInteger('admission_next_number')->default(1); $table->string('active_academic_year')->default('2026/2027'); $table->string('active_term')->default('Term 1'); $table->boolean('block_results_for_debtors')->default(false); $table->decimal('result_block_balance_threshold',12,2)->default(0); $table->timestamps();
        });
        Schema::create('school_classes', function (Blueprint $table) { $table->id(); $table->string('name')->unique(); $table->enum('level',['PRIMARY','JHS']); $table->unsignedTinyInteger('sort_order'); $table->foreignId('class_teacher_id')->nullable()->constrained('users')->nullOnDelete(); $table->boolean('active')->default(true); $table->timestamps(); });
        Schema::create('school_subjects', function (Blueprint $table) { $table->id(); $table->string('name'); $table->string('code')->unique(); $table->boolean('active')->default(true); $table->timestamps(); });
        Schema::create('teacher_assignments', function (Blueprint $table) { $table->id(); $table->foreignId('teacher_id')->constrained('users')->cascadeOnDelete(); $table->foreignId('school_class_id')->constrained()->cascadeOnDelete(); $table->foreignId('school_subject_id')->constrained()->cascadeOnDelete(); $table->timestamps(); $table->unique(['teacher_id','school_class_id','school_subject_id'],'teacher_assignment_unique'); });
        Schema::create('guardians', function (Blueprint $table) { $table->id(); $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $table->string('full_name'); $table->string('phone'); $table->string('email')->nullable(); $table->text('address')->nullable(); $table->timestamps(); });
        Schema::create('students', function (Blueprint $table) { $table->id(); $table->foreignId('user_id')->nullable()->unique()->constrained('users')->nullOnDelete(); $table->foreignId('guardian_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('school_class_id')->constrained()->restrictOnDelete(); $table->string('admission_number')->unique(); $table->string('first_name'); $table->string('middle_name')->nullable(); $table->string('last_name'); $table->enum('gender',['MALE','FEMALE']); $table->date('date_of_birth')->nullable(); $table->enum('student_type',['DAY','BOARDER']); $table->string('photo_path')->nullable(); $table->text('address')->nullable(); $table->date('admission_date'); $table->boolean('active')->default(true); $table->timestamps(); $table->index(['school_class_id','student_type']); });
        Schema::create('student_status_history', function (Blueprint $table) { $table->id(); $table->foreignId('student_id')->constrained()->cascadeOnDelete(); $table->enum('student_type',['DAY','BOARDER']); $table->timestamp('effective_at'); $table->foreignId('changed_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); });
        Schema::create('academic_scores', function (Blueprint $table) { $table->id(); $table->foreignId('student_id')->constrained()->cascadeOnDelete(); $table->foreignId('school_class_id')->constrained()->cascadeOnDelete(); $table->foreignId('school_subject_id')->constrained()->cascadeOnDelete(); $table->string('academic_year'); $table->string('term'); $table->decimal('class_score',5,2)->default(0); $table->decimal('exam_score',5,2)->default(0); $table->decimal('total_score',5,2)->default(0); $table->boolean('locked')->default(false); $table->timestamp('submitted_at')->nullable(); $table->foreignId('submitted_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('unlocked_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('unlocked_at')->nullable(); $table->timestamps(); $table->unique(['student_id','school_subject_id','academic_year','term'],'student_subject_term_unique'); });
        Schema::create('result_publications', function (Blueprint $table) { $table->id(); $table->foreignId('school_class_id')->constrained()->cascadeOnDelete(); $table->string('academic_year'); $table->string('term'); $table->boolean('published')->default(false); $table->timestamp('published_at')->nullable(); $table->foreignId('published_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->unique(['school_class_id','academic_year','term']); });
        Schema::create('fee_categories', function (Blueprint $table) { $table->id(); $table->string('name')->unique(); $table->boolean('boarding_only')->default(false); $table->boolean('active')->default(true); $table->timestamps(); });
        Schema::create('fee_assignments', function (Blueprint $table) { $table->id(); $table->foreignId('fee_category_id')->constrained()->restrictOnDelete(); $table->foreignId('school_class_id')->constrained()->cascadeOnDelete(); $table->enum('student_type',['ALL','DAY','BOARDER'])->default('ALL'); $table->string('academic_year'); $table->string('term'); $table->decimal('amount',12,2); $table->timestamps(); });
        Schema::create('payments', function (Blueprint $table) { $table->id(); $table->foreignId('student_id')->constrained()->restrictOnDelete(); $table->foreignId('fee_category_id')->nullable()->constrained()->nullOnDelete(); $table->string('academic_year'); $table->string('term'); $table->decimal('amount',12,2); $table->enum('method',['CASH','MOMO','BANK_TRANSFER']); $table->string('receipt_number')->unique(); $table->string('external_reference')->nullable(); $table->foreignId('received_by')->constrained('users')->restrictOnDelete(); $table->timestamp('paid_at'); $table->timestamps(); });
        Schema::create('audit_logs', function (Blueprint $table) { $table->id(); $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $table->string('action'); $table->string('record_type'); $table->unsignedBigInteger('record_id')->nullable(); $table->json('old_value')->nullable(); $table->json('new_value')->nullable(); $table->string('ip_address',45)->nullable(); $table->text('user_agent')->nullable(); $table->timestamp('created_at')->useCurrent(); $table->index(['record_type','record_id']); });
        Schema::create('sms_logs', function (Blueprint $table) { $table->id(); $table->foreignId('sent_by')->nullable()->constrained('users')->nullOnDelete(); $table->string('recipient'); $table->text('message'); $table->enum('status',['QUEUED','SENT','DELIVERED','FAILED'])->default('QUEUED'); $table->string('provider_reference')->nullable(); $table->text('failure_reason')->nullable(); $table->timestamps(); });
    }
    public function down(): void
    {
        foreach (['sms_logs','audit_logs','payments','fee_assignments','fee_categories','result_publications','academic_scores','student_status_history','students','guardians','teacher_assignments','school_subjects','school_classes','school_settings'] as $table) Schema::dropIfExists($table);
    }
};
